// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: entries.sql

package storage

import (
	"context"
	"database/sql"
)

const createEntry = `-- name: CreateEntry :exec
INSERT INTO entries (
    id,
    description,
    project_id,
    started_at,
    stopped_at,
    created_at,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7
)
`

type CreateEntryParams struct {
	ID          string
	Description string
	ProjectID   sql.NullString
	StartedAt   int64
	StoppedAt   sql.NullInt64
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) error {
	_, err := q.db.ExecContext(ctx, createEntry,
		arg.ID,
		arg.Description,
		arg.ProjectID,
		arg.StartedAt,
		arg.StoppedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createEntryTag = `-- name: CreateEntryTag :exec
INSERT INTO entry_tags (
    entry_id,
    tag_id,
    position
) VALUES (
    ?1,
    ?2,
    ?3
)
`

type CreateEntryTagParams struct {
	EntryID  string
	TagID    string
	Position int64
}

func (q *Queries) CreateEntryTag(ctx context.Context, arg CreateEntryTagParams) error {
	_, err := q.db.ExecContext(ctx, createEntryTag, arg.EntryID, arg.TagID, arg.Position)
	return err
}

const getActiveEntry = `-- name: GetActiveEntry :one
SELECT
    e.id,
    e.description,
    e.project_id,
    p.name AS project_name,
    e.started_at,
    e.stopped_at,
    e.created_at,
    e.updated_at
FROM entries e
LEFT JOIN projects p ON p.id = e.project_id
WHERE stopped_at IS NULL
LIMIT 1
`

type GetActiveEntryRow struct {
	ID          string
	Description string
	ProjectID   sql.NullString
	ProjectName sql.NullString
	StartedAt   int64
	StoppedAt   sql.NullInt64
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) GetActiveEntry(ctx context.Context) (GetActiveEntryRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveEntry)
	var i GetActiveEntryRow
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.ProjectID,
		&i.ProjectName,
		&i.StartedAt,
		&i.StoppedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEntryByID = `-- name: GetEntryByID :one
SELECT
    e.id,
    e.description,
    e.project_id,
    p.name AS project_name,
    e.started_at,
    e.stopped_at,
    e.created_at,
    e.updated_at
FROM entries e
LEFT JOIN projects p ON p.id = e.project_id
WHERE e.id = ?1
LIMIT 1
`

type GetEntryByIDRow struct {
	ID          string
	Description string
	ProjectID   sql.NullString
	ProjectName sql.NullString
	StartedAt   int64
	StoppedAt   sql.NullInt64
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) GetEntryByID(ctx context.Context, id string) (GetEntryByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getEntryByID, id)
	var i GetEntryByIDRow
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.ProjectID,
		&i.ProjectName,
		&i.StartedAt,
		&i.StoppedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const stopActiveEntry = `-- name: StopActiveEntry :execrows
UPDATE entries
SET
    stopped_at = ?1,
    updated_at = ?2
WHERE stopped_at IS NULL
    AND id = ?3
`

type StopActiveEntryParams struct {
	StoppedAt sql.NullInt64
	UpdatedAt int64
	ID        string
}

func (q *Queries) StopActiveEntry(ctx context.Context, arg StopActiveEntryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, stopActiveEntry, arg.StoppedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
