// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package storage

import (
	"database/sql"
)

type Entry struct {
	ID          string
	Description string
	ProjectID   sql.NullString
	StartedAt   string
	StoppedAt   sql.NullString
	CreatedAt   string
	UpdatedAt   string
}

type EntryTag struct {
	EntryID  string
	TagID    string
	Position int64
}

type Project struct {
	ID        string
	Name      string
	CreatedAt string
	UpdatedAt string
}

type Tag struct {
	ID        string
	Name      string
	CreatedAt string
	UpdatedAt string
}
