// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package storage

import (
	"database/sql"
)

type Entry struct {
	ID          string
	Description string
	ProjectID   sql.NullString
	StartedAt   int64
	StoppedAt   sql.NullInt64
	CreatedAt   int64
	UpdatedAt   int64
}

type EntryTag struct {
	EntryID  string
	TagID    string
	Position int64
}

type Project struct {
	ID        string
	Name      string
	CreatedAt int64
	UpdatedAt int64
}

type Tag struct {
	ID        string
	Name      string
	CreatedAt int64
	UpdatedAt int64
}
